# Generated by Django 5.0 on 2024-01-10 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_end', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_start_time', models.TimeField()),
                ('leave_end_date', models.DateField()),
                ('leave_end_time', models.TimeField()),
                ('leave_type', models.CharField(choices=[('Family', 'Family emergency'), ('Medical', 'Medical appointment'), ('Extended', 'Extended leave'), ('Maternity', 'Maternity leave'), ('ChildBirth', 'Child birth'), ('Sick', 'Sick leave')], max_length=20)),
                ('leave_reason', models.TextField()),
                ('leave_supporting_docs', models.FileField(blank=True, null=True, upload_to='leave_supporting_docs/')),
                ('leave_datetime_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('faculty_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_end.facultyshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_out', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('faculty_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_end.facultyshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
