# Generated by Django 4.2.5 on 2023-12-13 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_start_date', models.DateField()),
                ('leave_end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('Family', 'Family emergency'), ('Medical', 'Medical appointment'), ('Extended', 'Extended leave'), ('Maternity', 'Maternity leave'), ('ChildBirth', 'Child birth'), ('Sick', 'Sick leave')], max_length=20)),
                ('leave_reason', models.TextField()),
                ('leave_supporting_docs', models.FileField(blank=True, null=True, upload_to='leave_supporting_docs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
