# Generated by Django 4.1.6 on 2024-05-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='coursesection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timein',
            name='coursesection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timein',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
