# Generated by Django 4.1.6 on 2024-05-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
