# Generated by Django 5.0 on 2023-12-13 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('timein_status', models.CharField(choices=[('early', 'Early'), ('late', 'Late'), ('absent', 'Absent')], max_length=10)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('timeout_status', models.CharField(blank=True, choices=[('early', 'Early'), ('late', 'Late'), ('absent', 'Absent')], max_length=10, null=True)),
                ('location', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
