# Generated by Django 4.1.6 on 2024-05-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timein',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timein',
            name='faculty_shift',
        ),
        migrations.RemoveField(
            model_name='timein',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timeout',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='timeout',
            name='faculty_shift',
        ),
        migrations.RemoveField(
            model_name='timeout',
            name='semester',
        ),
    ]
