# Generated by Django 5.0 on 2024-01-07 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0002_initial'),
        ('faculty_end', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='place',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='user',
        ),
        migrations.CreateModel(
            name='TimeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('faculty_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_end.facultyshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_out', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('faculty_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_end.facultyshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Arrival',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Departure',
        ),
    ]
