# Generated by Django 5.0 on 2024-01-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='time_in',
            field=models.TimeField(),
        ),
    ]
