# Generated by Django 4.1.6 on 2024-05-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0002_alter_online_coursesection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='validation_comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timein',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='timein',
            name='validation_comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
