# Generated by Django 4.1.6 on 2024-05-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0002_online_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
