# Generated by Django 4.1.6 on 2024-05-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0002_remove_timein_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timeout',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
