# Generated by Django 5.0 on 2024-01-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0002_alter_arrival_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='time_out',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
