# Generated by Django 4.1.6 on 2024-05-23 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0002_timein_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timein',
            name='section',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timein',
            name='delay',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timein',
            name='month',
            field=models.CharField(max_length=50),
        ),
    ]
