# Generated by Django 5.0 on 2024-01-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0003_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein',
            name='time_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
