# Generated by Django 4.1.6 on 2024-05-10 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0003_alter_timein_status_alter_timeout_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timeout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
