# Generated by Django 4.1.6 on 2024-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0003_online_is_approved_online_validation_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='validation_comment',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
