# Generated by Django 5.0 on 2024-01-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0003_alter_departure_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
