# Generated by Django 4.1.6 on 2024-05-23 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty_end', '0003_timein_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='evidence',
        ),
        migrations.CreateModel(
            name='OnlineEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='evidence_images/')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('online_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_evidence', to='faculty_end.online')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
