# Generated by Django 4.1.6 on 2024-05-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0004_remove_online_evidence_onlineevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='is_red_instruction',
            field=models.BooleanField(default=False),
        ),
    ]
