# Generated by Django 5.0 on 2024-01-03 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0002_initial'),
        ('faculty_end', '0004_alter_departure_time_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_end.facultyshift'),
        ),
        migrations.AddField(
            model_name='departure',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_end.facultyshift'),
        ),
    ]
