# Generated by Django 4.1.6 on 2024-05-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0004_timein_created_at_timeout_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='timeout',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
