# Generated by Django 4.1.6 on 2024-05-24 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty_end', '0004_alter_online_validation_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complained_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complains', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('onsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onsite_complains', to='faculty_end.timein')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='evidence_images/')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('complain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complain_evidence', to='faculty_end.complains')),
                ('online', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_evidence', to='faculty_end.online')),
                ('onsite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onsite_evidence', to='faculty_end.timein')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OnlineEvidence',
        ),
    ]
