# Generated by Django 4.1.6 on 2024-05-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0005_complains_evidence_delete_onlineevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='onsite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onsite_complains', to='faculty_end.timein'),
        ),
    ]
