# Generated by Django 4.1.6 on 2024-05-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0005_online_is_red_instruction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineevidence',
            old_name='online_id',
            new_name='online',
        ),
    ]
