# Generated by Django 5.0 on 2024-01-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0005_arrival_shift_departure_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='shift',
        ),
    ]
