# Generated by Django 4.1.6 on 2024-05-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0006_rename_online_id_onlineevidence_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
