# Generated by Django 4.1.6 on 2024-05-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0006_alter_complains_onsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
