# Generated by Django 4.1.6 on 2024-05-22 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0006_remove_timein_worked_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timein',
            old_name='location',
            new_name='month',
        ),
        migrations.AddField(
            model_name='timein',
            name='room_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timein',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
