# Generated by Django 4.1.6 on 2024-05-22 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0007_rename_location_timein_month_timein_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='day',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
