# Generated by Django 4.1.6 on 2024-05-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0007_online_has_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timein',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
