# Generated by Django 4.1.6 on 2024-05-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0009_alter_online_validation_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApplication',
        ),
    ]
