# Generated by Django 4.1.6 on 2024-05-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0009_timein_delay_alter_timein_month_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='delay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='online',
            name='month',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='online',
            name='status',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='timein',
            name='delay',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timein',
            name='month',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timein',
            name='status',
            field=models.CharField(max_length=250),
        ),
    ]
