# Generated by Django 4.1.6 on 2024-05-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0010_alter_online_delay_alter_online_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='timein',
            name='delay',
        ),
        migrations.AlterField(
            model_name='online',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timein',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
