# Generated by Django 4.1.6 on 2024-05-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0011_remove_online_delay_remove_timein_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='delay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timein',
            name='delay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
