# Generated by Django 4.1.6 on 2024-05-23 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0011_remove_online_delay_remove_timein_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='delay',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='online',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_images/'),
        ),
        migrations.AddField(
            model_name='online',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timein',
            name='delay',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
