# Generated by Django 4.1.6 on 2024-05-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0012_online_delay_online_evidence_online_is_absent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
