# Generated by Django 4.1.6 on 2024-05-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0012_alter_online_acadhead_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='acadhead_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timein',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
