# Generated by Django 4.1.6 on 2024-05-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0013_timein_acadhead_created_at_alter_timein_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='checker_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
