# Generated by Django 4.1.6 on 2024-05-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0013_timein_acadhead_created_at_alter_timein_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='onsite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onsite_complains', to='faculty_end.timein'),
        ),
    ]
