# Generated by Django 4.1.6 on 2024-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0014_alter_complains_onsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='flag',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
