# Generated by Django 4.1.6 on 2024-05-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0014_timein_checker_created_at'),
        ('faculty_end', '0015_timein_flag'),
    ]

    operations = [
    ]
