# Generated by Django 4.1.6 on 2024-05-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0016_merge_0014_timein_checker_created_at_0015_timein_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timein',
            old_name='flag',
            new_name='justification_count',
        ),
        migrations.AddField(
            model_name='timein',
            name='acadhead_is_responded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
