# Generated by Django 4.1.6 on 2024-05-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0017_rename_flag_timein_justification_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='acadhead_is_responded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='online',
            name='justification_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
