# Generated by Django 4.1.6 on 2024-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0018_online_acadhead_is_responded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='online',
            name='justification_count',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
