# Generated by Django 4.1.6 on 2024-05-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0019_alter_online_justification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein',
            name='justification_count',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
