# Generated by Django 4.1.6 on 2024-05-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0020_alter_timein_justification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein',
            name='acadhead_is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
