# Generated by Django 4.1.6 on 2024-05-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0022_complains_created_at_evidence_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complains',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='created_at',
        ),
    ]
