# Generated by Django 4.1.6 on 2024-05-29 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0024_remove_workedhours_user_delete_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timein',
            name='submitted_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complains',
            name='onsite',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onsite_complains', to='faculty_end.timein'),
        ),
    ]
