# Generated by Django 4.1.6 on 2024-05-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0025_timein_submitted_complaint_alter_complains_onsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='submitted_complaint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='online',
            name='acadhead_is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
