# Generated by Django 4.1.6 on 2024-05-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0026_online_submitted_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complains',
            name='online',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_complains', to='faculty_end.online'),
        ),
    ]
