# Generated by Django 4.1.6 on 2024-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_end', '0028_complains_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='checker_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
