# Generated by Django 4.2.5 on 2024-01-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty_end', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='leave_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='faculty_end.leaveapplication'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.permission'),
        ),
    ]
