# Generated by Django 4.1.6 on 2024-05-25 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0003_alter_customuser_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyshift',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='facultyshift',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='facultyshift',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leaveapplicationaction',
            name='leave_application',
        ),
        migrations.RemoveField(
            model_name='leaveapplicationaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='qrcodegenerator',
            name='user',
        ),
        migrations.DeleteModel(
            name='AttendanceNotification',
        ),
        migrations.DeleteModel(
            name='FacultyShift',
        ),
        migrations.DeleteModel(
            name='LeaveApplicationAction',
        ),
        migrations.DeleteModel(
            name='QRCodeGenerator',
        ),
    ]
