# Generated by Django 5.0 on 2024-01-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0003_alter_approval_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
