# Generated by Django 5.0 on 2024-01-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0004_alter_approval_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(default=True, max_length=9),
        ),
    ]
