# Generated by Django 5.0 on 2024-01-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0007_alter_customuser_employment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(max_length=10),
        ),
    ]
