# Generated by Django 5.0 on 2024-01-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0008_alter_customuser_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approval_datetime',
            field=models.DateTimeField(default='2024-01-10 18:27:59'),
        ),
    ]
