# Generated by Django 5.0 on 2024-01-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0009_approval_approval_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='facultyshift',
            name='shift_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
