# Generated by Django 5.0 on 2024-01-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0010_alter_approval_approval_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
