# Generated by Django 4.2.9 on 2024-01-23 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0013_attendancenotification_time_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_firstname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_lastname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_picture',
        ),
    ]
