# Generated by Django 4.2.9 on 2024-01-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0014_remove_customuser_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(default='Full Time', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_firstname',
            field=models.CharField(default='James', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_lastname',
            field=models.CharField(default='Garlit', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/'),
        ),
    ]
