# Generated by Django 4.2.9 on 2024-01-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0015_customuser_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extension_name',
            field=models.CharField(default='Jr', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_middlename',
            field=models.CharField(default='Garlit', max_length=30),
        ),
    ]
