# Generated by Django 4.2.9 on 2024-01-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0016_customuser_extension_name_customuser_user_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employment_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='extension_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_middlename',
            field=models.CharField(max_length=30),
        ),
    ]
