# Generated by Django 4.1.6 on 2024-02-04 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0017_alter_customuser_employment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('faculty_id', models.IntegerField(unique=True)),
                ('faculty_fname', models.CharField(max_length=30)),
                ('faculty_mname', models.CharField(blank=True, max_length=30)),
                ('faculty_lname', models.CharField(max_length=30)),
                ('faculty_extname', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='faculty_pictures/')),
                ('faculty_type', models.CharField(max_length=20)),
            ],
        ),
    ]
