# Generated by Django 4.1.6 on 2024-02-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0018_facultyaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facultyaccount',
            name='faculty_extname',
        ),
        migrations.RemoveField(
            model_name='facultyaccount',
            name='faculty_fname',
        ),
        migrations.RemoveField(
            model_name='facultyaccount',
            name='faculty_lname',
        ),
        migrations.RemoveField(
            model_name='facultyaccount',
            name='faculty_mname',
        ),
        migrations.RemoveField(
            model_name='facultyaccount',
            name='faculty_type',
        ),
        migrations.RemoveField(
            model_name='facultyaccount',
            name='password',
        ),
        migrations.RemoveField(
            model_name='facultyaccount',
            name='picture',
        ),
    ]
