# Generated by Django 4.1.6 on 2024-02-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0019_remove_facultyaccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='extension_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_middlename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
