# Generated by Django 4.1.6 on 2024-02-06 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0021_alter_customuser_extension_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_start', models.DateField()),
                ('year_end', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='facultyshift',
            name='shift_day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facultyshift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_end.academicyear')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facultyshift',
            name='academic_year',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.CASCADE, to='admin_end.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facultyshift',
            name='semester',
            field=models.ForeignKey(default=2025, on_delete=django.db.models.deletion.CASCADE, to='admin_end.semester'),
            preserve_default=False,
        ),
    ]
