# Generated by Django 4.1.6 on 2024-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_end', '0022_academicyear_alter_facultyshift_shift_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='extension_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_middlename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
